### ISSUE TITLE
Multi-line conditional

### ISSUE THREAD

**Issue by shuttj** [neuland/jade4j#95]
This is more a question than an issue. Does jade and/or jade4j support multi-line conditional statements?

For example I have an if statement I would like to put each "or" condition on a new line so it's easier to read. Something like this.

```
if a
  || b
  || c
     p Hello
else
     p World
```

Obviously this is a contrived example and my conditions are much longer, but I am wondering if this is possible and I just haven't found the right syntax in my searching.

**Comment by naltatis** [comment]
No this is currently not possible. I think the cleanest way is to prepare the data in your model to eliminate the need of complex conditions inside the template.

Because jade4j is just the java implementation, discussions or suggestions like this should go through the original jade project.

\ naltatis
